### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by dmitrytokarev** [Haufe-Lexware/azure-apim-deployment-utils#2]
Without a license people need authors personal legal permission to use code.
I propose adding most simplistic license - MIT.

**Comment by dmitrytokarev** [comment]
From https://opensource.guide/legal/
`
If you don’t apply an open source license, everybody who contributes to your project also becomes an exclusive copyright holder of their work. That means nobody can use, copy, distribute, or modify their contributions – and that “nobody” includes you.
`

**Comment by DonMartin76** [comment]
Yep, sorry, I had totally missed out on this here. Apache 2.0 it is, will add in a minute.

**Comment by DonMartin76** [comment]
Apache 2.0 license added.

**Comment by dmitrytokarev** [comment]
Thank you!
